### PR TITLE
Rename lib module to 'MultiVolumeImporterLib'

### PR DESCRIPTION
**Pull request by jcfr**
This will avoid conflict when Slicer issue #3549 (Import scripted module
as python module) will be addressed.

### CODE REVIEW

**Comment by jcfr** [comment]
@fedorov If `MultiVolumeImporter` was not used outside of this module, this should not cause any issue.

**Comment by jcfr** [comment]
Thanks

**Comment by fedorov** [comment]
Thanks JC!

I updated SHA in Slicer in r24145.

**Comment by jcfr** [comment]
:+1:

**Pull request merged**
